### ISSUE TITLE
Where can I get this nbm?

### ISSUE THREAD

**Issue by insign** [RobinRadic/netbeans-laravel4-blade#1]

**Comment by RobinRadic** [comment]
The only thing that works are the {{-- blade comments --}}. I haven't had time lately to further develop this. So no .nbm file as it's still quite useless

**Comment by HexenZ** [comment]
Hi RobinRadic, I would like to know if you plan to continue with this project as it could help me a lot. Right now i'm using sublime text but it forces me to use two utilities. Thanks for all!

**Comment by RobinRadic** [comment]
Even though i fully intend to continue with this package i don't think it's gonna be anytime soon. I'm primarily using PhpStorm for web development. The 8.0 release of PhpStorm will include blade syntax highlighting. There's a bunch of other useful features that are missing from NB in terms of web-development, i'd highly recommend it.

**Comment by insign** [comment]
Sorry but, I never ever seen a best IDE than NetBeans. I tried PHPStorm but
it looks very polluted, I'll try it again.

_Hélio Araújo de Oliveira_
Evite correntes de e-mails e combata o spam.
Prefira materiais reciclados, incluindo papel

2014-05-23 23:07 GMT-03:00 Robin Radic notifications@github.com:

**Comment by mikadev** [comment]
how we can install your plugin ??

**Comment by RobinRadic** [comment]
Due to the fact that PHPStorm is so, so much better then NetBeans and because PHPStorm has Blade syntax highlighting + laravel plugin, i do not plan to continue with the project.

**Comment by PaolaRuby** [comment]
https://github.com/haidubogdan/netbeans-php-blade-plugin
